### PR TITLE
Build PRs on Concourse, not Travis

### PR DESCRIPTION
**Pull request by issyl0**
- This is the next step after building master on Concourse not Travis. To remove Travis entirely.

### CODE REVIEW

**Comment by issyl0** [comment]
Bah, `Your Ruby version is 2.6.1, but your Gemfile specified 2.5.3` is the error (yet the actual deploy job works fine?).

I tried upgrading the app to 2.6.1 and did a `bundle`, but `prometheus-client-mmap 0.9.1` failed to install which is required by `gds-metrics`.

**Comment by issyl0** [comment]
Shrug, it works now, it must be something locally for me that's broken.

**Comment by richardTowers** [comment]
Any reason for not heading for `2.6.2` (which is the latest version supported by PaaS currently)?

We'll probably drop support for `2.6.1` the next time the buildpacks get upgraded by the looks of https://github.com/cloudfoundry/ruby-buildpack/releases

**Comment by issyl0** [comment]
We could, but we'd need to [build a new Docker image](https://github.com/alphagov/tech-ops/blob/master/reliability-engineering/pipelines/internal-apps.yml#L149-L150) and I'm not sure how to do that currently. Definitely something we'll _need_ to do though.

I don't know the history behind why we use `gdsre/aws-ruby` and not another Ruby one, but I'm not tagging Toby to answer that question as he's on holiday. :-)

**Comment by richardTowers** [comment]
👍 sounds good to me in that case

**Comment by issyl0** [comment]
Thanks, @richardTowers!

**Pull request merged**
