### PR TITLE
Add Softwire as an allowed gds-users domain

### PR DESCRIPTION
**Pull request by OllieJC**
Adds "softwire.com" as an allowed gds-users domain _but_ not as an allowed log in domain

### CODE REVIEW

**Comment by Krenair** [comment]
What sort of JML process is in place for these?

**Comment by OllieJC** [comment]
> What sort of JML process is in place for these?

@Krenair - good question. Still be clarified but it'll likely involve processes with CO to manage, they'll request additions/removals.

**Comment by tlwr** [comment]
🍴 so the tests don't run

**Comment by tlwr** [comment]
Approved pending Alex is happy

**Comment by Krenair** [comment]
Making me happy with non-GDS users in gds-users might be a struggle, but I'm content with this if the relevant IA contact for whichever account(s) we expect these people to be accessing is :)

**Comment by OllieJC** [comment]
> with non-GDS users in gds-users
@Krenair - I had that same concern. Would have the requester or some other information as a tag against the user help?

**Comment by Krenair** [comment]
I'm not sure. Basically we should be notified when one of these people no longer works with GDS. The appropriate person should reach out to us. We can go and look at the GitHub PR to find out who originally requested them be added.

**Comment by OllieJC** [comment]
@Krenair - can this be merged?

**Comment by Krenair** [comment]
Has the JML process been clarified? Has the relevant IA contact approved this?

**Comment by OllieJC** [comment]
@Krenair Yes - CO to manage and provide at a two weekly security meeting. Yes - IA contact for IER, will DM you their name.

**Pull request merged**
